apiVersion: v1
kind: Service
metadata:
  name: {{ include "nopea.fullname" . }}-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nopea.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nopea.selectorLabels" . | nindent 4 }}
