kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nopea-dev
nodes:
  - role: control-plane
    extraPortMappings:
      # Webhook endpoint
      - containerPort: 30000
        hostPort: 4000
        protocol: TCP
